# Generated by Django 5.1.3 on 2024-11-20 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_pedido_quantidade_alter_pedido_consultorio_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="material",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="quantidade",
        ),
        migrations.CreateModel(
            name="PedidoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField()),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.produto"
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.pedido"
                    ),
                ),
            ],
        ),
    ]
