# Generated by Django 5.1.3 on 2024-11-25 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_material_rename_consultorio_pedido_departamento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedidoitem",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.produto"
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="numero",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="pedidoitem",
            name="pedido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens",
                to="main.pedido",
            ),
        ),
        migrations.DeleteModel(
            name="Material",
        ),
    ]
